pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo "Building using docker-compose..."
                sh "docker compose build"
            }
        }

        stage('Run') {
            steps {
                echo 'Starting container using docker-compose...'

                script {
                    sh """
                    cd application
                    # Stop old container if exists
                    docker compose down || true

                    # Start new one (detached)
                    docker compose up -d
                    """
                }
            }
        }
    }

    post {
        always {
            echo "Cleaning up..."
            //sh "docker compose down || true"
        }
    }
}
